name: Deploy to S3

on:
  push:
    branches:
      - main  # Trigger the workflow on push or pull request to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Build Tailwind CSS
      run: npm run build

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.118.2'  # Use the version of Hugo you are using

    - name: Build Hugo
      run: hugo --minify --baseURL="https://kotoblog.pp.ua"

    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude 'node_modules/*' --exclude 'package-lock.json' --exclude 'package.json' --exclude 'tailwind.config.js' --exclude 'input.css' --exclude '.git/*' --exclude '.github/*' --exclude '.gitignore'
      env:
        AWS_S3_BUCKET: kotoblog-website
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-central-1'

    - name: Invalidate CloudFront distribution
      run: |
        aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-central-1'
        CLOUDFRONT_DISTRIBUTION_ID: 555
